version: '3'

services:

  postgresql:
    image: "postgres:12"
    container_name: postgres_parsing
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5444:5432

volumes:
  pgdata: {}
